apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-dev
  namespace: platform-argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "app-dev-*"
  clusterResourceWhitelist: []
